In [1]:
%matplotlib qt
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
import time

# 2+1D Transport Equation

In [2]:
# Numerical Parameters

# Grid Points and Time Steps
N = int(1e2+1) # +1 for Off-By-One on Periodic BC
M = int(1e2+1)
T = int(5e2+1)
# Domain Size
L = 50
K = 50
# Domain
x = np.linspace(0, L, N)
y = np.linspace(0, K, M)
# Grid Size and Time Step Size
dx = x[2] - x[1]
dy = y[2] - y[1]
dt = 1e-2

lmbdx = dt/dx
lmbdy = dt/dy

# Coordinate Plane
xx,yy = np.meshgrid(x,y)
t = dt * T

In [3]:
# Memory Allocation
u = np.zeros((T,M,N))

In [4]:
# Inital Condition
rho_0 = 1
freq = 2*np.pi
freq_x = 2*freq/L
freq_y = 3*freq/K
uIC = rho_0 + 2*np.sin(freq_x*xx)+np.sin(freq_y*yy)
u[0] = np.copy(uIC)

Fx = 30
Fy = 20

print(lmbdx*Fx+lmbdy*Fy)
# print(u[0])

0.6 0.4


In [5]:
#Plotting
def plot(utt):
    fig = plt.figure(figsize=(15,15))
    ax = plt.axes(projection='3d')
    # ax.contour3D(xx, yy, uIC, 50, cmap='binary')
    # for elm in u:
    #     ax.contour3D(xx, yy, elm, 500, cmap='binary')
    ax.contour3D(xx,yy,utt,100)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('u')
    plt.show()

In [6]:
# # Solve

# st = time.time()

# for tt in range(0,T-1):
    
#     uU = np.roll(u,1,axis=1)
#     uD = np.roll(u,-1,axis=1)
#     uL = np.roll(u,1,axis=2)
#     uR = np.roll(u,-1,axis=2)

#     u[tt+1,:,0] = u[tt,:,0] - lmbdy*Fy*(u[tt,:,0]-u[tt,:,-1]) - lmbdx*Fx*(u[tt,:,0]-np.roll(u,1)[tt,:,0])
#     for jj in range(1,N):
#         u[tt+1,0,jj] = u[tt,0,jj] - lmbdy*Fy*(u[tt,0,jj]-u[tt,0,jj-1]) - lmbdx*Fx*(u[tt,0,jj]-u[tt,-1,jj])
#         for ii in range(1,M):
#             u[tt+1,ii,jj] = u[tt,ii,jj] - lmbdy*Fy*(u[tt,ii,jj]-u[tt,ii,jj-1]) - lmbdx*Fx*(u[tt,ii,jj]-u[tt,ii-1,jj])
            
# #     u[:,0] = u[:,0] - lmbdy*Fy*(u[:,0]-u[:,-1]) - lmbdx*Fx*(u[:,0]-np.roll(u,1)[:,0])
# #     for jj in range(1,M):
# #         u[0,jj] = u[0,jj] - lmbdy*Fy*(u[0,jj]-u[0,jj-1]) - lmbdx*Fx*(u[0,jj]-u[-1,jj])
# #         for ii in range(1,N):
# #             u[ii,jj] = u[ii,jj] - lmbdy*Fy*(u[ii,jj]-u[ii,jj-1]) - lmbdx*Fx*(u[ii,jj]-u[ii-1,jj])   

#     if tt % ((T-1)/10) == 0:
#         print(tt)
        
# et = time.time()

In [7]:
# Solve
st = time.time()
for tt in range(0,T-1):
    
#     uU = np.roll(u,1,axis=1)
#     uD = np.roll(u,-1,axis=1)
#     uL = np.roll(u,1,axis=2)
#     uR = np.roll(u,-1,axis=2)

#     u[tt+1] = (1-lmbdy*Fy*- lmbdx*Fx)*u[tt]+lmbdy*Fy*uD[tt]+lmbdx*Fx*uL[tt]

    for jj in range(0,M):
        for ii in range(0,N):
            u[tt+1,jj,ii] = u[tt,jj,ii] - lmbdy*Fy*(u[tt,jj,ii]-u[tt,jj-1,ii]) - lmbdx*Fx*(u[tt,jj,ii]-u[tt,jj,ii-1])


#     for jj in range(1,M):
#         u[tt+1,jj,0] = u[tt,jj,0] - lmbdy*Fy*(u[tt,jj,0]-u[tt,jj-1,0]) - lmbdx*Fx*(u[tt,jj,0]-u[tt,jj,-1])
#         for ii in range(1,N):
#             u[tt+1,jj,ii] = u[tt,jj,ii] - lmbdy*Fy*(u[tt,jj,ii]-u[tt,jj-1,ii]) - lmbdx*Fx*(u[tt,jj,ii]-u[tt,jj,ii-1])
            
# #     u[:,0] = u[:,0] - lmbdy*Fy*(u[:,0]-u[:,-1]) - lmbdx*Fx*(u[:,0]-np.roll(u,1)[:,0])
# #     for jj in range(1,M):
# #         u[0,jj] = u[0,jj] - lmbdy*Fy*(u[0,jj]-u[0,jj-1]) - lmbdx*Fx*(u[0,jj]-u[-1,jj])
# #         for ii in range(1,N):
# #             u[ii,jj] = u[ii,jj] - lmbdy*Fy*(u[ii,jj]-u[ii,jj-1]) - lmbdx*Fx*(u[ii,jj]-u[ii-1,jj])   

    if tt % ((T-1)/10) == 0:
        print(tt)
et = time.time()

elapsed_time = et - st
print('Execution time:', elapsed_time, 'seconds')

0
50
100
150
200
250
300
350
400
450
Execution time: 21.027485609054565 seconds


In [8]:
# # Solve
# st = time.time()
# for tt in range(0,T-1):
    
#     utt = u[tt].flatten()
    
#     for ij in range(N*M):
#         u[tt+1,ij] = (1-lmbdy*Fy*- lmbdx*Fx)*utt[ij]+lmbdy*Fy*utt[ij-1]+lmbdx*Fx*utt[ij-N]
# #     for jj in range(1,N):
# #         u[tt+1,0,jj] = u[tt,0,jj] - lmbdy*Fy*(u[tt,0,jj]-u[tt,0,jj-1]) - lmbdx*Fx*(u[tt,0,jj]-u[tt,-1,jj])
# #         for ii in range(1,M):
# #             u[tt+1,ii,jj] = u[tt,ii,jj] - lmbdy*Fy*(u[tt,ii,jj]-u[tt,ii,jj-1]) - lmbdx*Fx*(u[tt,ii,jj]-u[tt,ii-1,jj])
            
# #     u[:,0] = u[:,0] - lmbdy*Fy*(u[:,0]-u[:,-1]) - lmbdx*Fx*(u[:,0]-np.roll(u,1)[:,0])
# #     for jj in range(1,M):
# #         u[0,jj] = u[0,jj] - lmbdy*Fy*(u[0,jj]-u[0,jj-1]) - lmbdx*Fx*(u[0,jj]-u[-1,jj])
# #         for ii in range(1,N):
# #             u[ii,jj] = u[ii,jj] - lmbdy*Fy*(u[ii,jj]-u[ii,jj-1]) - lmbdx*Fx*(u[ii,jj]-u[ii-1,jj])   

#     if tt % ((T-1)/10) == 0:
#         print(tt)
# et = time.time()

# elapsed_time = et - st
# print('Execution time:', elapsed_time, 'seconds')

In [9]:
# #Plotting
# fig = plt.figure(figsize=(15,15))
# ax = plt.axes(projection='3d')
# # ax.contour3D(xx, yy, uIC, 50, cmap='binary')
# for elm in u:
#     ax.contour3D(xx, yy, elm, 500, cmap='binary')
# ax.set_xlabel('x')
# ax.set_ylabel('y')
# ax.set_zlabel('u')
# plt.show()

In [10]:
#Animation
import matplotlib.animation as animation
import networkx as nx
from matplotlib.animation import FuncAnimation, PillowWriter 

def change_plot(frame_number, u, plot):
   plot[0].remove()
   plot[0] = ax.plot_surface(xx, yy, u[frame_number,:,:], cmap="viridis")

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

plot = [ax.plot_surface(xx, yy, u[0, :, :], color='0.75', rstride=10, cstride=10)]
ax.set_zlim(np.min(u),np.max(u))

# ani = animation.FuncAnimation(fig, change_plot)

ani = animation.FuncAnimation(fig, change_plot, T, fargs=(u, plot), interval= 100, save_count=1000)
ani.save(filename=r"C:\Users\Chris Gerlach\OneDrive\Desktop\PDEmultidimension.gif", writer='pillow',fps=30)

plt.show()

In [11]:
# # converting to an html5 video
# video = ani.to_html5_video()
  
# # embedding for the video
# html = display.HTML(video)
  
# # draw the animation
# display.display(html)
# plt.show()

In [12]:
# #Animation

# import matplotlib.animation as animation

# plt.rcParams["figure.figsize"] = [7.50, 3.50]
# plt.rcParams["figure.autolayout"] = True

# N = 100
# fps = 1000
# frn = 50

# x = np.linspace(-4, 4, N + 1)
# x, y = np.meshgrid(x, x)
# zarray = np.zeros((N + 1, N + 1, frn))

# f = lambda x, y, sig: 1 / np.sqrt(sig) * np.exp(-(x ** 2 + y ** 2) / sig ** 2)

# for i in range(frn):
#    zarray[:, :, i] = f(x, y, 1.5 + np.sin(i * 2 * np.pi / frn))

# def change_plot(frame_number, zarray, plot):
#    plot[0].remove()
#    plot[0] = ax.plot_surface(x, y, zarray[:, :, frame_number], cmap="afmhot_r")

# fig = plt.figure()
# ax = fig.add_subplot(111, projection='3d')

# plot = [ax.plot_surface(x, y, zarray[:, :, 0], color='0.75', rstride=1, cstride=1)]

# ax.set_zlim(0, 1.1)
# ani = animation.FuncAnimation(fig, change_plot, frn, fargs=(zarray, plot), interval=1000 / fps)

# plt.show()

In [13]:
# # Domain
# def domain(Nx, Ny, x0, xf, y0, yf):
#     x = np.linspace(x0,xf, Nx+1)
#     y = np.linspace(y0,yf, Ny+1)
#     # z = np.linspace(z0,zf, Nz+1)
#     return x,y

# xx,yy = domain(200,200,-8,8,-8,8)
# x, y = np.meshgrid(xx,yy)
# z = np.sin(np.sqrt(x*x + y*y))

# fig = plt.figure(figsize=(15,15))
# ax = plt.axes(projection='3d')
# ax.scatter3D(x, y, z, c=z, cmap='Greens')

# ax.view_init(-90, 90)

# plt.show()

In [14]:
# TEST CELL
v = np.arange(0,9)
v = np.reshape(v,(3,3))
print(v)

vU = np.roll(v,1,axis=0)
vD = np.roll(v,-1,axis=0)
vL = np.roll(v,1,axis=1)
vR = np.roll(v,-1,axis=1)

print(vD[0,0],vU[0,0],vL[0,0],vR[0,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
3 6 2 1
