In [1]:
import numpy as np

a = np.arange(81)
a = np.reshape(a,(3,3,3,3))

b = np.arange(27,54)
b = np.reshape(b,(3,3,3))

def func(u):
    u = np.roll(u,1,axis=1)
    return u
    
print(b)
print(func(b))
a[:,0] = func(b[:])
print(a)

[[[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]]]
[[[33 34 35]
  [27 28 29]
  [30 31 32]]

 [[42 43 44]
  [36 37 38]
  [39 40 41]]

 [[51 52 53]
  [45 46 47]
  [48 49 50]]]
[[[[33 34 35]
   [27 28 29]
   [30 31 32]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[42 43 44]
   [36 37 38]
   [39 40 41]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[51 52 53]
   [45 46 47]
   [48 49 50]]

  [[63 64 65]
   [66 67 68]
   [69 70 71]]

  [[72 73 74]
   [75 76 77]
   [78 79 80]]]]
