In [1]:
import numpy as np
import pandas as pd

### Inner Products

a = np.arange(24).reshape(2,3,4)
print("Tensor a: ", a.shape, "\n", a)

b0 = np.ones(2)
b1 = np.ones(3)
b2 = np.ones(4)

print("Vector b0:", b0.shape, "\n", b0)
print("Vector b1:", b1.shape, "\n", b1)
print("Vector b2:", b2.shape, "\n", b2)

Tensor a:  (2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Vector b0: (2,) 
 [1. 1.]
Vector b1: (3,) 
 [1. 1. 1.]
Vector b2: (4,) 
 [1. 1. 1. 1.]


In [2]:
dot0 = np.tensordot(a, b0,axes=([0],[0]))
dot1 = np.tensordot(a, b1,axes=([1],[0]))
dot2 = np.tensordot(a, b2,axes=([2],[0]))
alt_dot2 = np.dot(a,b2)

print("Dot Product Along Axis 0:", dot0.shape, "\n", dot0)
print("Dot Product Along Axis 1:", dot1.shape, "\n", dot1)
print("Dot Product Along Axis 2:", dot2.shape, "\n", dot2)

Dot Product Along Axis 0: (3, 4) 
 [[12. 14. 16. 18.]
 [20. 22. 24. 26.]
 [28. 30. 32. 34.]]
Dot Product Along Axis 1: (2, 4) 
 [[12. 15. 18. 21.]
 [48. 51. 54. 57.]]
Dot Product Along Axis 2: (2, 3) 
 [[ 6. 22. 38.]
 [54. 70. 86.]]


In [3]:
dot01 = np.tensordot(dot0, b1, axes=([0],[0]))
dot02 = np.tensordot(dot0, b2, axes=([1],[0]))
dot12 = np.tensordot(dot1, b2, axes=([1],[0]))
dot21 = np.tensordot(dot2, b1, axes=([1],[0]))

print("Dot Product Along Axes 0 and 1:", dot01.shape, "\n", dot01)
print("Dot Product Along Axes 0 and 2:", dot02.shape, "\n", dot02)
print("Dot Product Along Axes 1 and 2:", dot12.shape, "\n", dot12)
print("Dot Product Along Axes 1 and 0:", dot21.shape, "\n", dot21)

Dot Product Along Axes 0 and 1: (4,) 
 [60. 66. 72. 78.]
Dot Product Along Axes 0 and 2: (3,) 
 [ 60.  92. 124.]
Dot Product Along Axes 1 and 2: (2,) 
 [ 66. 210.]
Dot Product Along Axes 1 and 0: (2,) 
 [ 66. 210.]


In [4]:
a_permute = np.transpose(a, (1, 0, 2))

print(a_permute.shape)
print(a_permute)

(3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [14]:
a = np.arange(24).reshape(2,3,4)
print("Tensor a: ", a.shape, "\n", a)

b = np.arange(12).reshape(4,3)
print("Matrix b:", b.shape, "\n", b)

Tensor a:  (2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Matrix b: (4, 3) 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
dot11 = np.tensordot(a, b, axes=([1],[1]))
dot20 = np.tensordot(a, b, axes=([2],[0]))

print("Dot Product Along Axis 1 of A & Axis 1 of B:", dot11.shape, "\n", dot11)
print("Dot Product Along Axis 2 of A & Axis 0 of B:", dot20.shape, "\n", dot20)

Dot Product Along Axis 1 of A & Axis 1 of B: (2, 4, 4) 
 [[[ 20  56  92 128]
  [ 23  68 113 158]
  [ 26  80 134 188]
  [ 29  92 155 218]]

 [[ 56 200 344 488]
  [ 59 212 365 518]
  [ 62 224 386 548]
  [ 65 236 407 578]]]
Dot Product Along Axis 2 of A & Axis 0 of B: (2, 3, 3) 
 [[[ 42  48  54]
  [114 136 158]
  [186 224 262]]

 [[258 312 366]
  [330 400 470]
  [402 488 574]]]


In [11]:
multi_dot12 = np.tensordot(a, b, axes=([1,2],[1,0]))
multi_dot21 = np.tensordot(a, b, axes=([2,1],[0,1]))
multi_dot = np.tensordot(a, b.T)

print("Dot Product Along Axis [1,2] of A & Axis [1,0] of B:", multi_dot12.shape, "\n", multi_dot12)
print("Dot Product Along Axis [2,1] of A & Axis [0,1] of B:", multi_dot21.shape, "\n", multi_dot21)
print("Dot Product Along Last N Axes of A & First N Axes of B:", multi_dot21.shape, "\n", multi_dot)

Dot Product Along Axis [1,2] of A & Axis [1,0] of B: (2,) 
 [ 440 1232]
Dot Product Along Axis [2,1] of A & Axis [0,1] of B: (2,) 
 [ 440 1232]
Dot Product Along Last N Axes of A & First N Axes of B: (2,) 
 [ 440 1232]


In [16]:
a = np.arange(720).reshape(2,3,4,5,6)
print("Tensor a: ", a.shape, "\n")

b = np.arange(720).reshape(2,3,4,5,6)
print("Matrix b:", b.shape, "\n")

dot1 = np.tensordot(a, b, axes = ([4],[4]))
dot2 = np.tensordot(a, b, axes = ([3,4],[3,4]))
dot3 = np.tensordot(a, b, axes = ([0,2,4],[0,2,4]))
dot4 = np.tensordot(a, b, axes = ([0,1,2,3,4],[0,1,2,3,4]))

headers = ["a Axes", "b Axes", "Resultant Shape", "Answer"]
ans = [["Last", "First", dot1.shape, ],
      ["Last 2", "First 2", dot2.shape, ],
      ["[2,4]", "[2,4]", dot3.shape, ],
      ["All", "All", dot4.shape, dot4],]

print(pd.DataFrame(ans,headers,headers))

Tensor a:  (2, 3, 4, 5, 6) 

Matrix b: (2, 3, 4, 5, 6) 

                 a Axes   b Axes           Resultant Shape     Answer
a Axes             Last    First  (2, 3, 4, 5, 2, 3, 4, 5)       None
b Axes           Last 2  First 2        (2, 3, 4, 2, 3, 4)       None
Resultant Shape   [2,4]    [2,4]              (3, 5, 3, 5)       None
Answer              All      All                        ()  124156920


In [19]:
permute_axes = (2, 4, 1, 3, 0)
permute_axes_arr = np.array(permute_axes)
b_permute = np.transpose(b, permute_axes)
print("Permuted Matrix B:", b_permute.shape, "\n")

a_dim_shape = np.arange(a.ndim)
b_dim_shape = np.arange(b.ndim)
a_permute_dim_shape = a_dim_shape[permute_axes_arr]
b_permute_dim_shape = b_dim_shape[permute_axes_arr]
print("A Axes to Sum Over: ", a_permute_dim_shape)
print("B Axes to Sum Over: ", a_permute_dim_shape)

permute_dot1 = np.tensordot(a, b, axes=(a_permute_dim_shape, b_permute_dim_shape))
permute_dot2 = np.tensordot(a, b_permute, axes=(a_permute_dim_shape, b_dim_shape))

print("Dot Product Along All Axes of Permuted A & All Axes of Permuted B:", permute_dot1.shape, "\n", permute_dot1)
print("Dot Product Along All Axes of A & All Axes of Permuted B:", permute_dot2.shape, "\n", permute_dot2)

Permuted Matrix B: (4, 6, 3, 5, 2) 

A Axes to Sum Over:  [2 4 1 3 0]
B Axes to Sum Over:  [2 4 1 3 0]
Dot Product Along All Axes of Permuted A & All Axes of Permuted B: () 
 124156920
Dot Product Along All Axes of A & All Axes of Permuted B: () 
 124156920


In [20]:
### Outer Products

